"""Run every query in SQL/02 and SQL/03 against Data/claims.db and write SQL/query_results.md."""
import re
import sqlite3
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
DB = ROOT / "Data" / "claims.db"
FILES = ["02_data_quality_checks.sql", "03_business_analysis.sql"]


def split_queries(sql_text):
    """Yield (title, sql) for each block that starts with a '-- Qn: title' comment."""
    blocks = re.split(r"^-- (Q\d+: .+)$", sql_text, flags=re.M)
    for title, body in zip(blocks[1::2], blocks[2::2]):
        yield title.strip(), body.strip()


def main():
    out = ["# SQL Query Results", "",
           "Generated by `Python/run_sql_queries.py` against `Data/claims.db` (SQLite).", ""]
    with sqlite3.connect(DB) as con:
        for name in FILES:
            out += [f"## {name}", ""]
            for title, sql in split_queries((ROOT / "SQL" / name).read_text()):
                df = pd.read_sql_query(sql, con)
                out += [f"### {title}", "", "```sql", sql, "```", "",
                        df.to_markdown(index=False, floatfmt=",.1f"), ""]
                print(f"{name[:2]} {title:<75} {len(df):>4} rows")
    (ROOT / "SQL" / "query_results.md").write_text("\n".join(out), encoding="utf-8")
    print("wrote SQL/query_results.md")


if __name__ == "__main__":
    main()
